version: "3.2"
volumes:
  postgres_automation:
  bundle_path_automation:
services:
  iot_db_automation:
    restart: on-failure:3
    image: postgres:13.2
    volumes:
      - postgres_automation:/var/lib/postgresql/data
    ports:
      - 5430:5432
    env_file:
      - enviroments/.env.postgresql
  iot_redis:
    restart: on-failure:3
    image: redis:alpine
    command: redis-server --requirepass vurokrazia
    ports:
      - "6378:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  iot_administration:
    restart:  on-failure:3
    build:
      context: ./automations_iot_administration
      dockerfile: dev.dockerfile
    ports:
      - "4000:3000"
      - "9022:9022"
    depends_on:
      - iot_redis
      - iot_db_automation
    stdin_open: true
    tty: true
    volumes:
      - ./automations_iot_administration:/home/developer/app
      - bundle_path_automation:/usr/local/bundle # New
    env_file:
      - enviroments/.env.iot_administration
  # iot_frontend_administration:
  #   restart:  on-failure:3
  #   build:
  #     context: ./automations_iot_frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./automations_iot_frontend:/app
  #   ports:
  #     - "4004:3000"
  #   stdin_open: true
  #   tty: true
  iot_sidekiq_administration:
    command: bundle exec sidekiq
    restart: on-failure:3
    image: automations_iot_iot_administration:latest
    depends_on:
      - iot_redis
      - iot_db_automation
    stdin_open: true
    tty: true
    volumes:
      - ./automations_iot_administration:/home/developer/app
      - bundle_path_automation:/usr/local/bundle # New
    env_file:
      - enviroments/.env.iot_administration
  iot_sidekiq_mailers:
    command: sh ./entrypoints/docker-entrypoint-sidekiq.sh
    restart: on-failure:3
    ports:
      - "25:25"
    image: automations_iot_iot_administration:latest
    depends_on:
      - iot_redis
      - iot_db_automation
    volumes:
      - ./automations_iot_administration:/home/developer/app
      - bundle_path_automation:/usr/local/bundle # New
    env_file:
      - enviroments/.env.iot_administration
  maildev:
    image: djfarrelly/maildev
    ports:
      - "90:80"